### ISSUE TITLE
Upgrade Spring Boot to the latest version

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-caching#21]
Update the guide to use the most recent Spring Boot version.

To do so, change the Spring Boot version in:

initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml

**Comment by zeze1004** [comment]
@Buzzardo Hi, I want to contribute this issue. Can I do it?  😄 😄 😄

**Comment by zeze1004** [comment]
@Buzzardo Plz review it🙇🏻

**Comment by robertmcnees** [comment]
Closing as this will be tracked at a higher level going forward.
