### ISSUE TITLE
Documentation Contribution

### ISSUE THREAD

**Issue by bootups** [spring-guides/gs-caching#3]
I documented your Spring Cache example, with some Sequence and Class Diagrams. The documentation can be seen at:
https://design.codelytics.io/?dashboardId=spring.cache.architecture
https://design.codelytics.io/?dashboardId=spring.cache.detail

Let me know if you think documentation would be useful for your readers.

**Comment by gregturn** [comment]
Thanks but since this guide focuses on code examples, I don't think sequence diagrams or class diagrams are what our readers need.
